[package]
name = "world_connection"
version = "0.1.0"
authors = ["XueBin Li"]

[dependencies]
# normal
chrono = "0.4.0"    # date and time
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
lazy_static = "1.0"

# log
log = "0.4.1"
fern = "0.5"        # Simple, efficient logging

#config
config = "0.8"

# web
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = "0.3"

hyper = "0.11"
futures = "0.1"
tokio-core = "0.1"

#test
mockers = "0.9.4"
mockers_macros = "0.9.4"
