[package]
name = "world_connection"
version = "0.1.0"
authors = ["XueBin Li"]

[dependencies]
chrono = "0.4.0"
serde_json = "1.0"

log = "0.4.1"
fern = "0.5"

hyper = "0.11"
futures = "0.1"
tokio-core = "0.1"
config = "0.8"
