[package]
name = "nature"
version = "0.0.1"
authors = ["XueBin Li"]

[dependencies]
# normal
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
lazy_static = "1.0"
uuid = { version = "0.6", features = ["v3"] }
lru_time_cache = "0.8"

libloading = "0.5.0"

# log
log = "0.4.1"
fern = "0.5"        # Simple, efficient logging

#config
config = "0.8"

# webup
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = "0.3"

# self project group
nature_common = {path = "../Nature-Common"}
nature_db = {path = "../Nature-DB"}

#[profile.test]
#debug = true