[package]
name = "nature"
version = "0.0.1"
authors = ["XueBin Li"]

[dependencies]
# normal
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
lazy_static = "1.0"
uuid = { version = "0.6", features = ["v3"] }
lru_time_cache = "0.8"
dotenv = "0.11"

# log
log = "0.4.1"
fern = "0.5"        # Simple, efficient logging

#config
config = "0.8"

# web
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = "0.3"

hyper = "0.11"
futures = "0.1"
tokio-core = "0.1"

# db
diesel = { version = "1.1", default-features = false, features = ["sqlite"] }
r2d2 = "0.8"
r2d2-diesel = "1.0"
cdrs = "1.2"
#rusqlite = {version = "0.13", features=["bundled"]}

#test
#mockers = "0.9.4"
#mockers_macros = "0.9.4"
